export const EXPENSE_REPOSITORY = Symbol('EXPENSE_REPOSITORY');
export const CREATE_EXPENSE_USE_CASE = Symbol('CREATE_EXPENSE_USE_CASE');
export const LIST_USER_EXPENSES_USE_CASE = Symbol('LIST_USER_EXPENSES_USE_CASE');
export const GET_EXPENSE_USE_CASE = Symbol('GET_EXPENSE_USE_CASE');
export const UPDATE_EXPENSE_USE_CASE = Symbol('UPDATE_EXPENSE_USE_CASE');
export const DELETE_EXPENSE_USE_CASE = Symbol('DELETE_EXPENSE_USE_CASE');
