import {
  CONTACT_CREATE_OWN_PERMISSION,
  CONTACT_DELETE_OWN_PERMISSION,
  CONTACT_READ_OWN_PERMISSION,
  CONTACT_UPDATE_OWN_PERMISSION,
  NOTE_CREATE_OWN_PERMISSION,
  NOTE_DELETE_OWN_PERMISSION,
  NOTE_READ_OWN_PERMISSION,
  NOTE_UPDATE_OWN_PERMISSION,
  TODO_CREATE_OWN_PERMISSION,
  TODO_DELETE_OWN_PERMISSION,
  TODO_READ_OWN_PERMISSION,
  TODO_UPDATE_OWN_PERMISSION,
} from './permission-name.constants';
import { DEFAULT_ROLE_PERMISSION_MAP } from './role-permission-map';
import { ADMIN_ROLE_NAME, STUDENT_ROLE_NAME } from './role-name.constants';

describe('DEFAULT_ROLE_PERMISSION_MAP', () => {
  it('grants full own-resource CRUD for student users', () => {
    expect(DEFAULT_ROLE_PERMISSION_MAP[STUDENT_ROLE_NAME]).toEqual([
      TODO_CREATE_OWN_PERMISSION,
      TODO_READ_OWN_PERMISSION,
      TODO_UPDATE_OWN_PERMISSION,
      TODO_DELETE_OWN_PERMISSION,
      NOTE_CREATE_OWN_PERMISSION,
      NOTE_READ_OWN_PERMISSION,
      NOTE_UPDATE_OWN_PERMISSION,
      NOTE_DELETE_OWN_PERMISSION,
      CONTACT_CREATE_OWN_PERMISSION,
      CONTACT_READ_OWN_PERMISSION,
      CONTACT_UPDATE_OWN_PERMISSION,
      CONTACT_DELETE_OWN_PERMISSION,
    ]);
  });

  it('keeps admin access inclusive of student CRUD permissions', () => {
    expect(DEFAULT_ROLE_PERMISSION_MAP[ADMIN_ROLE_NAME]).toEqual(
      expect.arrayContaining(DEFAULT_ROLE_PERMISSION_MAP[STUDENT_ROLE_NAME]),
    );
  });
});
