export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const PASSWORD_POLICY = Symbol('PASSWORD_POLICY');
export const REGISTER_USER_USE_CASE = Symbol('REGISTER_USER_USE_CASE');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const USER_ACCESS_READER = Symbol('USER_ACCESS_READER');
export const AUTH_SESSION_REPOSITORY = Symbol('AUTH_SESSION_REPOSITORY');
export const ACCESS_TOKEN_ISSUER = Symbol('ACCESS_TOKEN_ISSUER');
export const OPAQUE_TOKEN_GENERATOR = Symbol('OPAQUE_TOKEN_GENERATOR');
export const OPAQUE_TOKEN_HASHER = Symbol('OPAQUE_TOKEN_HASHER');
export const AUTHENTICATE_USER_USE_CASE = Symbol('AUTHENTICATE_USER_USE_CASE');
export const REFRESH_AUTH_SESSION_USE_CASE = Symbol(
  'REFRESH_AUTH_SESSION_USE_CASE',
);
export const LOGOUT_AUTH_SESSION_USE_CASE = Symbol(
  'LOGOUT_AUTH_SESSION_USE_CASE',
);
export const GET_CURRENT_USER_USE_CASE = Symbol('GET_CURRENT_USER_USE_CASE');
export const ADMIN_USER_MANAGEMENT = Symbol('ADMIN_USER_MANAGEMENT');
export const RBAC_CATALOG = Symbol('RBAC_CATALOG');
export const RESETTABLE_DOMAINS = Symbol('RESETTABLE_DOMAINS');
export const LIST_ADMIN_USERS_USE_CASE = Symbol('LIST_ADMIN_USERS_USE_CASE');
export const GET_ADMIN_USER_USE_CASE = Symbol('GET_ADMIN_USER_USE_CASE');
export const CREATE_ADMIN_USER_USE_CASE = Symbol('CREATE_ADMIN_USER_USE_CASE');
export const UPDATE_ADMIN_USER_ROLES_USE_CASE = Symbol(
  'UPDATE_ADMIN_USER_ROLES_USE_CASE',
);
export const UPDATE_ADMIN_USER_STATUS_USE_CASE = Symbol(
  'UPDATE_ADMIN_USER_STATUS_USE_CASE',
);
export const LIST_ROLES_USE_CASE = Symbol('LIST_ROLES_USE_CASE');
export const CREATE_ROLE_USE_CASE = Symbol('CREATE_ROLE_USE_CASE');
export const UPDATE_ROLE_USE_CASE = Symbol('UPDATE_ROLE_USE_CASE');
export const DELETE_ROLE_USE_CASE = Symbol('DELETE_ROLE_USE_CASE');
export const LIST_PERMISSIONS_USE_CASE = Symbol('LIST_PERMISSIONS_USE_CASE');
export const CREATE_PERMISSION_USE_CASE = Symbol(
  'CREATE_PERMISSION_USE_CASE',
);
export const UPDATE_PERMISSION_USE_CASE = Symbol(
  'UPDATE_PERMISSION_USE_CASE',
);
export const DELETE_PERMISSION_USE_CASE = Symbol(
  'DELETE_PERMISSION_USE_CASE',
);
export const RESET_ADMIN_DATA_USE_CASE = Symbol('RESET_ADMIN_DATA_USE_CASE');
export const DEMO_USER_SEEDER = Symbol('DEMO_USER_SEEDER');
export const SEED_DEMO_USERS_USE_CASE = Symbol('SEED_DEMO_USERS_USE_CASE');
