export const CONTACT_REPOSITORY = Symbol('CONTACT_REPOSITORY');
export const CREATE_CONTACT_USE_CASE = Symbol('CREATE_CONTACT_USE_CASE');
export const LIST_USER_CONTACTS_USE_CASE = Symbol('LIST_USER_CONTACTS_USE_CASE');
export const GET_CONTACT_USE_CASE = Symbol('GET_CONTACT_USE_CASE');
export const UPDATE_CONTACT_USE_CASE = Symbol('UPDATE_CONTACT_USE_CASE');
export const DELETE_CONTACT_USE_CASE = Symbol('DELETE_CONTACT_USE_CASE');
