export const MOVIE_REPOSITORY = Symbol('MOVIE_REPOSITORY');
export const CREATE_MOVIE_USE_CASE = Symbol('CREATE_MOVIE_USE_CASE');
export const LIST_USER_MOVIES_USE_CASE = Symbol('LIST_USER_MOVIES_USE_CASE');
export const GET_MOVIE_USE_CASE = Symbol('GET_MOVIE_USE_CASE');
export const UPDATE_MOVIE_USE_CASE = Symbol('UPDATE_MOVIE_USE_CASE');
export const DELETE_MOVIE_USE_CASE = Symbol('DELETE_MOVIE_USE_CASE');
